[package]
name = "explode"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
config = "0.15.9"
serde = { version = "1.0.219", features = ["derive"] }
tinytemplate = "1.2.1"
